export const types = {
   SEARCH_WORD: "SEARCH_WORD",
   SEARCH_WORD_FOUND: "SEARCH_WORD_FOUND",
   SEARCH_WORD_NOT_FOUND: "SEARCH_WORD_NOT_FOUND",
   SEARCH_WORD_ERROR: "SEARCH_WORD_ERROR",
   FETCH_WORD: "FETCH_WORD",
   FETCH_WORD_SUCCESS: "FETCH_WORD_SUCCESS",
   FETCH_WORD_ERROR: "FETCH_WORD_ERROR",
   UPDATE_WORD: "UPDATE_WORD",
   CACHE_WORD_AUDIO: "CACHE_WORD_AUDIO",
   CACHE_WORD_AUDIO_SUCCESS: "CACHE_WORD_AUDIO_SUCCESS",
   CACHE_WORD_AUDIO_ERROR: "CACHE_WORD_AUDIO_ERROR",
   DOWNLOAD_AUDIO_FILE: "DOWNLOAD_FILE",
   DOWNLOAD_AUDIO_FILE_SUCCESS: "DOWNLOAD_FILE_SUCCESS",
   DOWNLOAD_AUDIO_FILE_ERROR: "DOWNLOAD_FILE_ERROR"
};